### ISSUE TITLE
An exception occurred during a WebClient request.. Retrying in one second... 

### ISSUE THREAD

**Issue by KKica** [anasb1/NuSave#3]
Its been retrying for a while now.
I build the solution and tried the example in the repo.

Downloading
Newtonsoft.Json 9.0.1
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...
An exception occurred during a WebClient request.. Retrying in one second...

**Comment by jcprogrammer480** [comment]
I am also facing same issue.

**Comment by anasb1** [comment]
@KKica @jcprogrammer480 could you please give more details about your development environment?
- OS
- .NET Framework version
- Are you using a proxy?

**Comment by anasb1** [comment]
This is confirmed as a bug.

**Comment by anasb1** [comment]
Issue fixed, @KKica @jcprogrammer480 please let me know if it's working for you now.
